USE TOKYO;

CREATE TABLE BAND (
  ID INT AUTO_INCREMENT,
  NAME VARCHAR(110) NOT NULL UNIQUE,
  PATH_IMAGE VARCHAR(150) UNIQUE,
  DATA_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(ID)
);

CREATE TABLE DESCRIPTION(
  ID INT AUTO_INCREMENT,
  ID_BAND INT NOT NULL,
  DESCRIPTION_BAND TEXT NOT NULL,
  DATA_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(ID),
  FOREIGN KEY(ID_BAND) REFERENCES BAND(ID),
);

CREATE TABLE ALBUM (
  ID INT AUTO_INCREMENT,
  ID_BAND INT NOT NULL,
  NAME VARCHAR(110) NOT NULL UNIQUE,
  PATH_IMAGE VARCHAR(150) UNIQUE,
  DATA_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(ID),
  FOREIGN KEY(ID_BAND) REFERENCES BAND(ID)
);

CREATE TABLE MUSIC (
  ID INT AUTO_INCREMENT,
  ID_BAND INT NOT NULL,
  NAME VARCHAR(110) NOT NULL UNIQUE,
  PATH_IMAGE VARCHAR(110) UNIQUE,
  DATA_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(ID),
  FOREIGN KEY(ID_BAND) REFERENCES BAND(ID)
);

INSERT INTO `BAND`(
  `NAME`
) VALUES  ('SOAD'), ('Slipknot'), ('Men at Work'), ('Angra'), ('Gojira'), ('Saliva');

INSERT INTO `MUSIC`(
  `ID_BAND`, `NAME`
) VALUES (1, 'Chop Suey'), (2, 'Dead Mememories'), (3, 'Overhead'), (4, 'Time'), (5, 'Vacuity'), 
  (6, 'Click Click Boom');
