USE TOKYO;

CREATE TABLE BAND (
  ID INT AUTO_INCREMENT,
  NAME VARCHAR(110) NOT NULL UNIQUE,
  PATH_IMAGE VARCHAR(150) UNIQUE,
  DATA_TIME DATETIME,
  PRIMARY KEY(ID)
);

CREATE TABLE DESCRIPTION(
  ID INT AUTO_INCREMENT,
  ID_BAND INT NOT NULL,
  DESCRIPTION_BAND TEXT NOT NULL,
  DATA_TIME DATETIME,
  PRIMARY KEY(ID),
  FOREIGN KEY(ID_BAND) REFERENCES BAND(ID)
);

CREATE TABLE ALBUM (
  ID INT AUTO_INCREMENT,
  ID_BAND INT NOT NULL,
  NAME VARCHAR(110) NOT NULL UNIQUE,
  PATH_IMAGE VARCHAR(150) UNIQUE,
  DATE_TIME DATETIME,
  PRIMARY KEY(ID),
  FOREIGN KEY(ID_BAND) REFERENCES BAND(ID)
);

CREATE TABLE MUSIC (
  ID INT AUTO_INCREMENT,
  ID_BAND INT NOT NULL,
  NAME VARCHAR(110) NOT NULL UNIQUE,
  PATH_IMAGE VARCHAR(110) UNIQUE,
  DATE_TIME DATETIME,
  PRIMARY KEY(ID),
  FOREIGN KEY(ID_BAND) REFERENCES BAND(ID)
);
